# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 03:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_auto_20160914_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 14, 3, 11, 41, 138996, tzinfo=utc)),
        ),
    ]
